import React from 'react';
const ClientesActuales = () => {
    return (

    <table className='solicitud-cita-caj-tabla'>
        <tbody>
            <tr className='solicitud-cita-caj-tabla-titulo'>
                <th>Fecha inicio</th>
                <th>Tipo contrato</th>
                <th>Nombre</th>
                <th>Teléfono</th>
                <th>Propiedad</th>
                <th>Dirección</th>
                <th>Monto</th>
                <th></th>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>999999999999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>999999999999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>999999999999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>999999999999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>999999999999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>999999999999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>999999999999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>999999999999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>999999999999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>999999999999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>999999999999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>999999999999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>999999999999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>999999999999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>999999999999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>999999999999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>999999999999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>999999999999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>999999999999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>999999999999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>999999999999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>999999999999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>999999999999</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>$9999999</td>
            </tr>


 


        </tbody>
    </table>
    )
}
export default ClientesActuales