import React from 'react';
const HistoricoPropiedades = () => {
    return (

    <table className='solicitud-cita-caj-tabla'>
        <tbody>
            <tr className='solicitud-cita-caj-tabla-titulo'>
                <th>Fecha ingreso</th>
                <th>Fecha venta</th>
                <th>Estado</th>
                <th>Propiedad</th>
                <th>Dirección</th>
                <th>Cant hab.</th>
                <th>Baños</th>
                <th>Monto</th>
                <th></th>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>--------</td>
                <td>Disponible</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>99</td>
                <td>99</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>99/99/9999</td>
                <td>Vendida</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>99</td>
                <td>99</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>--------</td>
                <td>Disponible</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>99</td>
                <td>99</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>99/99/9999</td>
                <td>Vendida</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>99</td>
                <td>99</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>--------</td>
                <td>Disponible</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>99</td>
                <td>99</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>99/99/9999</td>
                <td>Vendida</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>99</td>
                <td>99</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>--------</td>
                <td>Disponible</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>99</td>
                <td>99</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>99/99/9999</td>
                <td>Vendida</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>99</td>
                <td>99</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>--------</td>
                <td>Disponible</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>99</td>
                <td>99</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>99/99/9999</td>
                <td>Vendida</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>99</td>
                <td>99</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>--------</td>
                <td>Disponible</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>99</td>
                <td>99</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>99/99/9999</td>
                <td>Vendida</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>99</td>
                <td>99</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>--------</td>
                <td>Disponible</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>99</td>
                <td>99</td>
                <td>$9999999</td>
            </tr>
            <tr>
                <td>99/99/999</td>
                <td>99/99/9999</td>
                <td>Vendida</td>
                <td>xxxxxxxxxxxxx</td>
                <td>xxxxxxxxxxxxx</td>
                <td>99</td>
                <td>99</td>
                <td>$9999999</td>
            </tr>


 


        </tbody>
    </table>
    )
}
export default HistoricoPropiedades